version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: compup
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: password

  flyway:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://db:5432/compup -user=dbuser -password=password migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
