version: '2.4'
services:
  db:
    image: postgres
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      timeout: 45s
      interval: 1s
      retries: 10
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - '${RABBITMQ_UI_PORT}:15672'
      - '${RABBITMQ_PORT}:5672'
  mail:
    image: dockage/mailcatcher
    ports:
      - ${MAIL_WEB_UI}:1080
      - ${SMTP_PORT}:1025
  wait_for_dependencies:
    image: alpine
    depends_on:
      db:
        condition: service_healthy