name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: shared - install
      working-directory: ./packages/shared
      run: npm i
    - name: shared - build
      working-directory: ./packages/shared
      run: npm run build

    - name: pgtyped - install
      working-directory: ./packages/pgtyped
      run: npm i
    - name: pgtyped - build
      working-directory: ./packages/pgtyped
      run: npm run build

    - name: browser-app - install
      working-directory: ./packages/browser-app
      run: npm i
    - name: browser-app - lint
      working-directory: ./packages/browser-app
      run: npm run lint
    - name: browser-app - test
      working-directory: ./packages/browser-app
      run: ENV_FILE=.env.test npm run test

    - name: server-app - install
      working-directory: ./packages/server-app
      run: npm i
    - name: server-app - lint
      working-directory: ./packages/server-app
      run: npm run lint
    - name: server-app - Setup infrastructure
      working-directory: ./packages/server-app
      run: ENV_FILE=.env.test npm run infrastructure:up
    - name: server-app - test
      working-directory: ./packages/server-app
      run: ENV_FILE=.env.test npm run test
